version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: itinerary-client
    ports:
      - "3111:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: itinerary-server
    volumes:
      - ./client:/app/data
    networks:
      - app-network
    environment:
      NODE_ENV: development
      PORT: 3002

networks:
  app-network:
    driver: bridge
